//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Xades.Test.IntModule {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:types:v1")]
    public partial class FaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultCodeField;
        
        private string faultSourceField;
        
        private StringLangType messageField;
        
        private DetailType[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FaultSource {
            get {
                return this.faultSourceField;
            }
            set {
                this.faultSourceField = value;
                this.RaisePropertyChanged("FaultSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public StringLangType Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Detail", IsNullable=false)]
        public DetailType[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:types:v1")]
    public partial class StringLangType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:types:v1")]
    public partial class DetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string detailCodeField;
        
        private string detailSourceField;
        
        private string locationField;
        
        private StringLangType messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DetailCode {
            get {
                return this.detailCodeField;
            }
            set {
                this.detailCodeField = value;
                this.RaisePropertyChanged("DetailCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DetailSource {
            get {
                return this.detailSourceField;
            }
            set {
                this.detailSourceField = value;
                this.RaisePropertyChanged("DetailSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public StringLangType Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:types:v1")]
    public partial class Blob : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private string contentEncodingField;
        
        private string messageNameField;
        
        private byte[] hashValueField;
        
        private string idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("ContentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContentEncoding {
            get {
                return this.contentEncodingField;
            }
            set {
                this.contentEncodingField = value;
                this.RaisePropertyChanged("ContentEncoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageName {
            get {
                return this.messageNameField;
            }
            set {
                this.messageNameField = value;
                this.RaisePropertyChanged("MessageName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] HashValue {
            get {
                return this.hashValueField;
            }
            set {
                this.hashValueField = value;
                this.RaisePropertyChanged("HashValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:be:cin:nip:tools:xades", ConfigurationName="IntModule.XadesTools")]
    public interface XadesTools {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:cin:nip:tools:xades:createXadesT:detail", ReplyAction="urn:be:cin:nip:tools:xades:createXadesT:signature")]
        [System.ServiceModel.FaultContractAttribute(typeof(IM.Xades.Test.IntModule.FaultType), Action="urn:be:cin:nip:tools:xades:createXadesT:fault", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IM.Xades.Test.IntModule.createXadesTResponse createXadesT(IM.Xades.Test.IntModule.createXadesTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (createXadesTResponse) of message createXadesBesResponse does not match the default value (createXadesBes)
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:cin:nip:tools:xades:createXadesBes:detail", ReplyAction="urn:be:cin:nip:tools:xades:createXadesBes:signature")]
        [System.ServiceModel.FaultContractAttribute(typeof(IM.Xades.Test.IntModule.FaultType), Action="urn:be:cin:nip:tools:xades:createXadesBes:fault", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IM.Xades.Test.IntModule.createXadesTResponse createXadesBes(IM.Xades.Test.IntModule.createXadesBesRequest request);
        
        // CODEGEN: Parameter 'Xadest' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:be:cin:nip:tools:xades:verifyXadesT:signature", ReplyAction="urn:be:cin:nip:tools:xades:verifyXadesT:result")]
        [System.ServiceModel.FaultContractAttribute(typeof(IM.Xades.Test.IntModule.FaultType), Action="urn:be:cin:nip:tools:xades:verifyXadesT:fault", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IM.Xades.Test.IntModule.verifyXadesTResponse verifyXadesT(IM.Xades.Test.IntModule.verifyXadesTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createXadesT", WrapperNamespace="urn:be:cin:nip:tools:xades", IsWrapped=true)]
    public partial class createXadesTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:tools:xades", Order=0)]
        public IM.Xades.Test.IntModule.Blob ResponseDetail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:tools:xades", Order=1)]
        public IM.Xades.Test.IntModule.Blob RequestDetail;
        
        public createXadesTRequest() {
        }
        
        public createXadesTRequest(IM.Xades.Test.IntModule.Blob ResponseDetail, IM.Xades.Test.IntModule.Blob RequestDetail) {
            this.ResponseDetail = ResponseDetail;
            this.RequestDetail = RequestDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createXadesTResponse", WrapperNamespace="urn:be:cin:nip:tools:xades", IsWrapped=true)]
    public partial class createXadesTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:tools:xades", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] @return;
        
        public createXadesTResponse() {
        }
        
        public createXadesTResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createXadesBes", WrapperNamespace="urn:be:cin:nip:tools:xades", IsWrapped=true)]
    public partial class createXadesBesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:tools:xades", Order=0)]
        public IM.Xades.Test.IntModule.Blob ResponseDetail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:tools:xades", Order=1)]
        public IM.Xades.Test.IntModule.Blob RequestDetail;
        
        public createXadesBesRequest() {
        }
        
        public createXadesBesRequest(IM.Xades.Test.IntModule.Blob ResponseDetail, IM.Xades.Test.IntModule.Blob RequestDetail) {
            this.ResponseDetail = ResponseDetail;
            this.RequestDetail = RequestDetail;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:be:cin:nip:tools:xades")]
    public partial class VerificationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultMajorField;
        
        private string resultMinorField;
        
        private string resultMessageField;
        
        private System.DateTime timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string ResultMajor {
            get {
                return this.resultMajorField;
            }
            set {
                this.resultMajorField = value;
                this.RaisePropertyChanged("ResultMajor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string ResultMinor {
            get {
                return this.resultMinorField;
            }
            set {
                this.resultMinorField = value;
                this.RaisePropertyChanged("ResultMinor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
                this.RaisePropertyChanged("ResultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyXadesT", WrapperNamespace="urn:be:cin:nip:tools:xades", IsWrapped=true)]
    public partial class verifyXadesTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:tools:xades", Order=0)]
        public IM.Xades.Test.IntModule.Blob Detail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:tools:xades", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Xades-t", DataType="base64Binary")]
        public byte[] Xadest;
        
        public verifyXadesTRequest() {
        }
        
        public verifyXadesTRequest(IM.Xades.Test.IntModule.Blob Detail, byte[] Xadest) {
            this.Detail = Detail;
            this.Xadest = Xadest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyXadesTResponse", WrapperNamespace="urn:be:cin:nip:tools:xades", IsWrapped=true)]
    public partial class verifyXadesTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:be:cin:nip:tools:xades", Order=0)]
        public IM.Xades.Test.IntModule.VerificationResult @return;
        
        public verifyXadesTResponse() {
        }
        
        public verifyXadesTResponse(IM.Xades.Test.IntModule.VerificationResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XadesToolsChannel : IM.Xades.Test.IntModule.XadesTools, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XadesToolsClient : System.ServiceModel.ClientBase<IM.Xades.Test.IntModule.XadesTools>, IM.Xades.Test.IntModule.XadesTools {
        
        public XadesToolsClient() {
        }
        
        public XadesToolsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XadesToolsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XadesToolsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XadesToolsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IM.Xades.Test.IntModule.createXadesTResponse IM.Xades.Test.IntModule.XadesTools.createXadesT(IM.Xades.Test.IntModule.createXadesTRequest request) {
            return base.Channel.createXadesT(request);
        }
        
        public byte[] createXadesT(IM.Xades.Test.IntModule.Blob ResponseDetail, IM.Xades.Test.IntModule.Blob RequestDetail) {
            IM.Xades.Test.IntModule.createXadesTRequest inValue = new IM.Xades.Test.IntModule.createXadesTRequest();
            inValue.ResponseDetail = ResponseDetail;
            inValue.RequestDetail = RequestDetail;
            IM.Xades.Test.IntModule.createXadesTResponse retVal = ((IM.Xades.Test.IntModule.XadesTools)(this)).createXadesT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IM.Xades.Test.IntModule.createXadesTResponse IM.Xades.Test.IntModule.XadesTools.createXadesBes(IM.Xades.Test.IntModule.createXadesBesRequest request) {
            return base.Channel.createXadesBes(request);
        }
        
        public byte[] createXadesBes(IM.Xades.Test.IntModule.Blob ResponseDetail, IM.Xades.Test.IntModule.Blob RequestDetail) {
            IM.Xades.Test.IntModule.createXadesBesRequest inValue = new IM.Xades.Test.IntModule.createXadesBesRequest();
            inValue.ResponseDetail = ResponseDetail;
            inValue.RequestDetail = RequestDetail;
            IM.Xades.Test.IntModule.createXadesTResponse retVal = ((IM.Xades.Test.IntModule.XadesTools)(this)).createXadesBes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IM.Xades.Test.IntModule.verifyXadesTResponse IM.Xades.Test.IntModule.XadesTools.verifyXadesT(IM.Xades.Test.IntModule.verifyXadesTRequest request) {
            return base.Channel.verifyXadesT(request);
        }
        
        public IM.Xades.Test.IntModule.VerificationResult verifyXadesT(IM.Xades.Test.IntModule.Blob Detail, byte[] Xadest) {
            IM.Xades.Test.IntModule.verifyXadesTRequest inValue = new IM.Xades.Test.IntModule.verifyXadesTRequest();
            inValue.Detail = Detail;
            inValue.Xadest = Xadest;
            IM.Xades.Test.IntModule.verifyXadesTResponse retVal = ((IM.Xades.Test.IntModule.XadesTools)(this)).verifyXadesT(inValue);
            return retVal.@return;
        }
    }
}
